function [] = stereo_matching(data)

save_to = "../results/stereo " + string(datetime) + ".mat";


switch data
    case 1
        im0_path = 'https://vision.middlebury.edu/stereo/data/scenes2014/datasets/Motorcycle-perfect/im0.png';
        im1_path = 'https://vision.middlebury.edu/stereo/data/scenes2014/datasets/Motorcycle-perfect/im1.png';
        
        isotropic = true;
        L = 5;
        lmb = 20;
        
        ndisps = 30;
        dscl1 = 2;
        dscl2 = 2;
        
        iter_max = 30;
        
        backend = prost.backend.pdhg(...
            'stepsize', 'boyd', ...
            'alg2_gamma', 0,...
            'arb_delta', 1.05,...                
            'arb_tau', 0.8,... 
            'arg_alpha0', 0.5,... 
            'arg_delta', 1.5,... 
            'arg_nu', 0.95, ...             
            'residual_iter', 10, ...
            'scale_steps_operator', 1, ...
            'sigma0', 0.01, ...
            'tau0', 100);
        cost_volume = compute_stereo_cost(im0_path, im1_path, ndisps, dscl1, dscl2);
        
    case 2
        im0_path = 'https://vision.middlebury.edu/stereo/data/scenes2014/datasets/Umbrella-perfect/im0.png';
        im1_path = 'https://vision.middlebury.edu/stereo/data/scenes2014/datasets/Umbrella-perfect/im1.png';
        
        isotropic = true;
        L = 5;
        lmb = 10;
                
        ndisps = 30;
        dscl1 = 2;
        dscl2 = 2;
        
        iter_max = 60;
        
        backend = prost.backend.pdhg(...
            'stepsize', 'boyd', ...
            'alg2_gamma', 0,...
            'arb_delta', 1.05,...                
            'arb_tau', 0.8,... 
            'arg_alpha0', 0.5,... 
            'arg_delta', 1.5,... 
            'arg_nu', 0.95, ...             
            'residual_iter', 200, ...
            'scale_steps_operator', 1, ...
            'sigma0', 0.005, ...
            'tau0', 200);
        cost_volume = compute_stereo_cost(im0_path, im1_path, ndisps, dscl1, dscl2);
        
    case 3
        im0_path = 'https://vision.middlebury.edu/stereo/data/scenes2014/datasets/Backpack-perfect/im0.png';
        im1_path = 'https://vision.middlebury.edu/stereo/data/scenes2014/datasets/Backpack-perfect/im1.png';
        
        isotropic = true;
        L = 5;
        lmb = 12;
        
        ndisps = 30;
        dscl1 = 2;
        dscl2 = 2;
        
        iter_max = 60;
        
        backend = prost.backend.pdhg(...
            'stepsize', 'boyd', ...
            'alg2_gamma', 0,...
            'arb_delta', 1.05,...                
            'arb_tau', 0.8,... 
            'arg_alpha0', 0.5,... 
            'arg_delta', 1.5,... 
            'arg_nu', 0.95, ...             
            'residual_iter', 200, ...
            'scale_steps_operator', 1, ...
            'sigma0', 0.005, ...
            'tau0', 200);
        cost_volume = compute_stereo_cost(im0_path, im1_path, ndisps, dscl1, dscl2);
        
    case 4
        im0_path = '../images/rainbow_isotropic_0.png';
        im1_path = '../images/rainbow_isotropic_1.png';
        
       
        isotropic = true;      
        L = 5;
        lmb = 7;
        
        iter_max = 10;
        
        backend = prost.backend.pdhg(...
            'stepsize', 'alg2', ...
            'alg2_gamma', 1.0e-05,...
            'arb_delta', 1.05,...                
            'arb_tau', 0.8,... 
            'arg_alpha0', 0.5,... 
            'arg_delta', 1.5,... 
            'arg_nu', 0.95, ...             
            'residual_iter', 50, ...
            'scale_steps_operator', 1, ...
            'sigma0', 1/151, ...
            'tau0', 150);
        
        cost_volume = compute_stereo_cost_no_deriv(im1_path, im0_path, 10, 1);

        
    case 5
        im0_path = '../images/rainbow_anisotropic_0.png';
        im1_path = '../images/rainbow_anisotropic_1.png';
           
        isotropic = false;        
        L = 5;
        lmb = 7;
        
        iter_max = 10;
        
        backend = prost.backend.pdhg(...
            'stepsize', 'alg2', ...
            'alg2_gamma', 1.0e-05,...
            'arb_delta', 1.05,...                
            'arb_tau', 0.8,... 
            'arg_alpha0', 0.5,... 
            'arg_delta', 1.5,... 
            'arg_nu', 0.95, ...             
            'residual_iter', 50, ...
            'scale_steps_operator', 1, ...
            'sigma0', 1/151, ...
            'tau0', 150);
        
        cost_volume = compute_stereo_cost_no_deriv(im1_path, im0_path, 10, 1);
end

gamma = linspace(0, 1, L)'; 
sublabel_lifting_convex_breg(cost_volume, gamma, lmb, iter_max, isotropic, save_to, backend)


% visualize
uk = load(save_to, 'uk');
figure
hold off

for i = 1:iter_max
    imshow(uk.uk{i})
    colormap(jet(256))
    axis off
    title("Iteration k = "+num2str(i))
    pause(2)
end


